In [2]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#import Dataset
dataset = pd.read_csv('50_Startups.csv')

In [4]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
#Data preprocessing
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

In [6]:
#Encoding the categorical variabel
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder
labelEncoder_X = LabelEncoder()
X[:,3] = labelEncoder_X.fit_transform(X[:,3])
onehotEncoder = OneHotEncoder(categorical_features = [3])
X = onehotEncoder.fit_transform(X).toarray()

C:\Users\Aadhil\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Aadhil\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:450: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [7]:
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [8]:
#avoid dummy variable trap
X = X[:,1:]

In [9]:
#Splitting the dataset in to training and testing set
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test   = train_test_split(X,y,test_size = 1/3 , random_state=0)

In [10]:
#fitting Mutiple linear regression to Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train )

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
#predict the Test result
y_pred = regressor.predict(X_test)

In [12]:
y_pred

array([111616.64259451, 132709.39466316, 140155.11033793,  76099.20398184,
       186329.94240372, 112822.19807256,  63002.00394805,  99107.10428091,
       119287.75473384, 175522.83864739, 101000.69861501,  85772.99293235,
       117713.76481525,  90230.88085202, 133375.04389452, 167530.54765829,
       158013.54602063])

In [13]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 , 155752.6 , 132602.65])

In [14]:
print('Coefficients:', regressor.coef_)
# The mean squared error
print("Mean squared error: %.2f" % np.mean((regressor.predict(X_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regressor.score(X_test, y_test))

Coefficients: [ 5.92663381e+03 -3.38231256e+02  8.28371991e-01  5.03972419e-02
  2.21861926e-02]
Mean squared error: 118348525.67
Variance score: 0.88


In [25]:
#Building the optimal model using backward elimination
#import statsmodels.formula.api as sm
import statsmodels.api as sm
X = np.append(arr=np.ones((50,1)).astype(int), values=X,axis=1)

In [30]:
X_opt= X[:, [0,1,2,3,4,5]]
regressor_OLS = sm.OLS(endog=y , exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.4
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           2.76e-29
Time:                        22:07:07   Log-Likelihood:                -527.35
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.625e+04   1013.373     16.036      0.000    1.42e+04    1.83e+04
x1          1.625e+04   1013.373     16.036      0.000    1.42e+04    1.83e+04
x2          1.625e+04   1013.373     16.036      0.000    1.42e+04    1.83e+04
x3          1163.8663   3379.767      0.344      0.732   -5639.252    7966.985
x4             9.5969   3312.045      0.003      0.998   -6657.204    6676.398
x5             0.8530      0.030     28.226      0.000       0.792       0.914
==============================================================================
Omnibus:                       13.418   Durbin-Watson:                   1.122
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.605
Skew:                          -0.907   Prob(JB):                     0.000150
Kurtosis:                       5.271   Cond. No.                     1.01e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.71e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [31]:
X_opt= X[:, [0,1,2,4,5]]
regressor_OLS = sm.OLS(endog=y , exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     416.4
Date:                Thu, 10 Dec 2020   Prob (F-statistic):           1.26e-30
Time:                        22:07:25   Log-Likelihood:                -527.42
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      47   BIC:                             1067.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.64e+04    903.607     18.152      0.000    1.46e+04    1.82e+04
x1           1.64e+04    903.607     18.152      0.000    1.46e+04    1.82e+04
x2           1.64e+04    903.607     18.152      0.000    1.46e+04    1.82e+04
x3          -560.3051   2841.908     -0.197      0.845   -6277.486    5156.876
x4             0.8545      0.030     28.843      0.000       0.795       0.914
==============================================================================
Omnibus:                       14.030   Durbin-Watson:                   1.127
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.472
Skew:                          -0.916   Prob(JB):                     5.91e-05
Kurtosis:                       5.448   Cond. No.                     8.70e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.95e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""